# Alembic Configuration File
# For more information visit http://alembic.sqlalchemy.org

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the icalendar package.
# Note that this value is ignored if version_path_separator is set to something other than ":"
# (the default) with SQLAlchemy 1.1 is used as engine.
# timezone =

# max length of characters to apply to the
# "slug" field
# Note that the default value of -1 indicates
# there is no length limit
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be treated as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Loggers to configure in alembic.ini.
# Set to DEBUG to see detailed migration output
[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

# Custom additions for AIDI
sqlalchemy.url = driver://user:password@localhost/dbname
