apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ollama.fullname" . }}-pvc
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
