# Root Account State Backend Configuration
# This file is generated by create-state-backend.sh and should not be edited manually
terraform {
  backend "s3" {
    # These values will be replaced by the script
    bucket         = "deallus-tfstate-root-REPLACE_ACCOUNT_ID"
    key            = "root/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "deallus-tfstate-lock-root"
  }
}
